// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClientOnly: typeof import('./src/components/ClientOnly.vue')['default']
    PwaReloadPrompt: typeof import('./src/components/base/modal/PwaReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VButton: typeof import('./src/components/base/button/VButton.vue')['default']
    VButtons: typeof import('./src/components/base/button/VButtons.vue')['default']
    VCard: typeof import('./src/components/base/card/VCard.vue')['default']
    VPlaceload: typeof import('./src/components/base/loader/VPlaceload.vue')['default']
  }
}
